### PR TITLE
adding ci tests

### PR DESCRIPTION
**Pull request by lemire**

### CODE REVIEW

**Comment by camel-cdr** [comment]
@lemire Does ~~"name: Ubuntu RISC-V"~~ "arch: riscv64" give you a RISC-V system? If it does, does it support rvv?

I think it's safer to use cross-compilation with qemu, this would allow us to test with multiple vector lengths.

I'll try to set up the ci for this repository.

**Comment by lemire** [comment]
> "arch: riscv64" give you a RISC-V system? If it does, does it support rvv?

It provides a QEMU 64-bit RISC-V emulator running the latest Ubuntu: https://www.qemu.org/docs/master/system/target-riscv.html

> I think it's safer to use cross-compilation with qemu, this would allow us to test with multiple vector lengths.

I am not very concerned with details but I often find it easier to use ready-made GitHub actions.

**Comment by camel-cdr** [comment]
I'll continue this tomorrow. The version I've got now worked in docker, but apparently github doesn't allow modifying `/etc/apt/sources.list`.
The problem is that ubuntu-latest doesn't have clang-17, that is solved by your suggestions, but it also doesn't have a qemu build that supports rvv. I don't know any better way to install a newer qemu, other than building from source.

**Comment by camel-cdr** [comment]
@lemire  Ok, I figured it out, the ci test works now, see: https://github.com/camel-cdr/simdutf/actions/runs/8122950210

Does [this](https://github.com/camel-cdr/simdutf/blob/master/.github/workflows/rvv-clang-17.yml) look good, or should we also enable asan and test with different vector lengths?

**Comment by lemire** [comment]
> Does [this](https://github.com/camel-cdr/simdutf/blob/master/.github/workflows/rvv-clang-17.yml) look good, or should we also enable asan and test with different vector lengths?

Everything else being equal, the more tests, the better *but* the trade-off is longer running tests... so we want to balance things out and not go overboard.

**Comment by camel-cdr** [comment]
Ok, I wasn't able to get the sanitizers to work with qemu, so I've now added two test runs, one with the minimum VLEN and one with the maximum VLEN that qemu supports (128, and 1024).

**Pull request closed without merging**
